# Generated by Django 4.2.4 on 2023-09-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertising2',
        ),
        migrations.DeleteModel(
            name='Advertising3',
        ),
        migrations.DeleteModel(
            name='Advertising4',
        ),
    ]
